site: Lena Song

url: https://songlena.github.io
baseurl: ""

collections:
  pages:
    output: true
    permalink: https://songlena.github.io/:name
  posts:
    output: true
    permalink: https://songlena.github.io/blog/:slug
  projects:
    output: true
    permalink: https://songlena.github.io/project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "_pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "_projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
  
